### ISSUE TITLE
Is the warning about makechrootpkg still relevant

### ISSUE THREAD

**Issue by danielshub** [aurutils/aurutils#1145]
With the resolution of https://gitlab.archlinux.org/archlinux/devtools/-/merge_requests/114?commit_id=84a45a5124ddce7e0b7db92edeb90f0e05308965 is the warning in the aur-chroot man page

> Warning: Due to bugs in makechrootpkg, a NOPASSWD rule for /usr/bin/makechrootpkg is equivalent to NOPASSWD: ALL.

still relevant?

**Comment by danielshub** [comment]
Of course why would they want to address a bug, that apparently exists on the Arch build servers, that gives trivial privilege escalation when the person who reports the bug provides a clean patch and promptly replies to feedback on the patch.

It looks like there is only a merge request and no bug report/issue associated with the merge request. Do you think that reporting it as an "issue" would help? Is there anything that can be done to get them to merge your patch?

Thanks for your work on aurutils.

**Comment by AladW** [comment]
I don't think devtools has much interest in user feedback - the devs only merge what they have immediate need for. More specifically, I was told there is no interest in merging this "because there are other escalation vectors anyway". Though none so trivial as the one I pointed out :)

When phoronix writes about compromised packages from the Arch build server, you can link to this issue :smile:
