### ISSUE TITLE
`aur sync -c` does not work

### ISSUE THREAD

**Issue by nl6720** [aurutils/aurutils#1151]
After upgrading from aurutils 19-1 to aurutils 19.2-1, `aur sync -c` doesn't work anymore. No output is produced at all.

See attached logs of:

```
$ AUR_DEBUG=1 aur sync -c aurutils
```
[aurutils-19.2-1-bad.log](https://github.com/aurutils/aurutils/files/14807192/aurutils-19.2-1-bad.log)
[aurutils-19-1-good.log](https://github.com/aurutils/aurutils/files/14807193/aurutils-19-1-good.log)

**Comment by ardhinata** [comment]
I'm also can reproduce this issue with `aur sync -cu`. My mitigation right now is downgrading aurutils version 19.2 to 19.1 and add `IgnorePkg=aurutils` to `/etc/pacman.conf` to pin aurutils version.

I'm also attaching debug logs for comparison:
[aurutils-19.1.log](https://github.com/aurutils/aurutils/files/14807796/aurutils-19.1.log)
[aurutils-19.2-fail.log](https://github.com/aurutils/aurutils/files/14807798/aurutils-19.2-fail.log)

**Comment by AladW** [comment]
It makes no sense to me that it would work in 19.1, but not 19.2. The only thing that changed is https://github.com/aurutils/aurutils/commit/6f9181710f616699ef2b6f2a2ba7ac571ea393c9

Does reverting that commit fix the issue?

**Comment by nl6720** [comment]
6f9181710f616699ef2b6f2a2ba7ac571ea393c9 is bork while eb664e70101e72d639d4ef5446d35b55db232deb works fine.

**Comment by AladW** [comment]
Fixed in 19.3

**Comment by AladW** [comment]
Cleared the mystery: `type -P` prints the command name to standard output, and this resulted in `aur chroot --status` printing six lines instead of the (expected) three. This in turn leads to a SIGPIPE in `wait $!`: https://github.com/aurutils/aurutils/blob/master/lib/aur-build#L226

Using `hash` or `command -p` as suggested on IRC would help, or just redirect standard output to `/dev/null`. That said, I think adding these diagnostics - when the required commands can easily be retrieved from say, `pacman -F` - was premature anyway.

I've added an additional error message to avoid future confusion: db906f3cf39efdaeee9406a23986844d969757af
